name: Build and push Docker wait-for-terraform-plan image

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (default is: latest)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - dev
env:
  IMAGE_NAME_TF_PLAN: ghcr.io/resourcely-inc/wait-for-terraform-plan:${{ inputs.tag }}

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Build and push wait-for-terraform-plan
    - name: Checkout wait-for-terraform-plan code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        repository: Resourcely-Inc/wait-for-terraform-plan
        ref: main
        path: wait-for-terraform-plan

    - name: Build wait-for-terraform-plan Docker image
      run: |
        docker build -t $IMAGE_NAME_TF_PLAN --build-arg="GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}" wait-for-terraform-plan
        docker images # for debugging purposes

    # Login and push both images
    - name: Login to Github Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push wait-for-terraform-plan Docker Image to Github Container Registry
      run: docker push $IMAGE_NAME_TF_PLAN

